#define VIEWPORT_W (safeZoneX + safeZoneW) 
#define VIEWPORT_H (safeZoneY + safeZoneH)

// Dialog mode, possible values:
// CENTER_CENTER
// TOP_LEFT
// TOP_CENTER
// TOP_RIGHT
// LEFT_CENTER
// RIGHT_CENTER
// BOTTOM_LEFT
// BOTTOM_CENTER
// BOTTOM_RIGHT

#ifdef CENTER_CENTER 
    #define RELATIVE_X(RELATIVE_POSITION) (CENTER_X - ((DIALOG_W / 2 + DIALOG_M * 2) - (RELATIVE_POSITION + DIALOG_M)) * GRID_W)
    #define RELATIVE_Y(RELATIVE_POSITION) (CENTER_Y - ((DIALOG_H / 2 + DIALOG_M * 2) - (RELATIVE_POSITION + DIALOG_M)) * GRID_H)
    #undef CENTER_CENTER
#endif

#ifdef TOP_LEFT
	#define RELATIVE_X(RELATIVE_POSITION) ((safeZoneX) + DIALOG_M * GRID_W + RELATIVE_POSITION * GRID_W)
    #define RELATIVE_Y(RELATIVE_POSITION) ((safeZoneY) + DIALOG_M * GRID_H + RELATIVE_POSITION * GRID_H)
    #undef TOP_LEFT
#endif

#ifdef TOP_CENTER
	#define RELATIVE_X(RELATIVE_POSITION) (CENTER_X - ((DIALOG_W / 2 + DIALOG_M * 2) - (RELATIVE_POSITION + DIALOG_M)) * GRID_W)
	#define RELATIVE_Y(RELATIVE_POSITION) ((safeZoneY) + DIALOG_M * GRID_H + RELATIVE_POSITION * GRID_H)
    #undef TOP_CENTER
#endif

#ifdef TOP_RIGHT
	#define RELATIVE_X(RELATIVE_POSITION) ((VIEWPORT_W) - DIALOG_M * GRID_W - DIALOG_W * GRID_W + RELATIVE_POSITION * GRID_W)
    #define RELATIVE_Y(RELATIVE_POSITION) ((safeZoneY) + DIALOG_M * GRID_H + RELATIVE_POSITION * GRID_H)
    #undef TOP_RIGHT
#endif

#ifdef LEFT_CENTER
	#define RELATIVE_X(RELATIVE_POSITION) ((safeZoneX) + DIALOG_M * GRID_W + RELATIVE_POSITION * GRID_W)
    #define RELATIVE_Y(RELATIVE_POSITION) (CENTER_Y - ((DIALOG_H / 2 + DIALOG_M * 2) - (RELATIVE_POSITION + DIALOG_M)) * GRID_H)
    #undef LEFT_CENTER
#endif

#ifdef RIGHT_CENTER
	#define RELATIVE_X(RELATIVE_POSITION) ((VIEWPORT_W) - DIALOG_M * GRID_W - DIALOG_W * GRID_W + RELATIVE_POSITION * GRID_W)
    #define RELATIVE_Y(RELATIVE_POSITION) (CENTER_Y - ((DIALOG_H / 2 + DIALOG_M * 2) - (RELATIVE_POSITION + DIALOG_M)) * GRID_H)
    #undef RIGHT_CENTER
#endif

#ifdef BOTTOM_LEFT
	#define RELATIVE_X(RELATIVE_POSITION) ((safeZoneX) + DIALOG_M * GRID_W + RELATIVE_POSITION * GRID_W)
    #define RELATIVE_Y(RELATIVE_POSITION) ((VIEWPORT_H) - DIALOG_M * GRID_H - DIALOG_H * GRID_H + RELATIVE_POSITION * GRID_H)
    #undef BOTTOM_LEFT
#endif

#ifdef BOTTOM_CENTER
	#define RELATIVE_X(RELATIVE_POSITION) (CENTER_X - ((DIALOG_W / 2 + DIALOG_M * 2) - (RELATIVE_POSITION + DIALOG_M)) * GRID_W)
	#define RELATIVE_Y(RELATIVE_POSITION) ((VIEWPORT_H) - DIALOG_M * GRID_H - DIALOG_H * GRID_H + RELATIVE_POSITION * GRID_H)
    #undef BOTTOM_CENTER
#endif

#ifdef BOTTOM_RIGHT
	#define RELATIVE_X(RELATIVE_POSITION) ((VIEWPORT_W) - DIALOG_M * GRID_W - DIALOG_W * GRID_W + RELATIVE_POSITION * GRID_W)
	#define RELATIVE_Y(RELATIVE_POSITION) ((VIEWPORT_H) - DIALOG_M * GRID_H - DIALOG_H * GRID_H + RELATIVE_POSITION * GRID_H)
    #undef BOTTOM_RIGHT
#endif

#define SCALE_X(UNSCALED_SIZE) ((UNSCALED_SIZE) * GRID_W)
#define SCALE_Y(UNSCALED_SIZE) ((UNSCALED_SIZE) * GRID_H)


